### ISSUE TITLE
Enum from_primitive should accept strings

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-python#56]
Enum `from_primitive` should accept strings as input and map them to corresponding enum values.

It should also be possible to do,

```
MyEnum('ITEM_NAME')
```

And have it map to the value.

**Comment by recht** [comment]
The interesting thing is that thriftrw-go will serialize enums as strings when marshalling to json, but the python version doesn't accept strings. I realize that thrift to json is completely undefined, but it's pretty annoying that thriftrw does two very different and incompatibe things.

**Comment by abhinav** [comment]
Fair point. The inconsistent behavior between the two ThriftRW versions is not
ideal, but as you said, Thrift-JSON conversion is undefined and unsupported. I
don't think we should spend effort making it compatible.

The more support we add for JSON, the more people will rely on it, and the
more compatibility issues they will run into. Case in point: We added
Unmarshal/MarshalJSON support to ThriftRW Go enums and now we're having this
conversation. I think we would prefer to keep the Thrift-as-JSON-schema can
closed.

All that said, if you really need this, we'll be happy to review a PR adding
support for strings to the `from_primitive` method for enums.

CC @kriskowal @akshayjshah
